[tool.black]
line-length = 100
target-version = ['py311']
include = '.pyi?$'
exclude = '''
/(
    .git
  | .venv
  | venv
  | migrations
  | pycache
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv", "migrations", ".git"]