name: Backend CI/CD

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev --ignore-pipfile

    - name: Verify pytest is installed
      run: |
        pipenv run pip list | grep pytest

    - name: Run tests
      run: |
        pipenv run pytest ./tests -v


  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  # only runs if tests pass ✅
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'


    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/v1/services/rnd_A9m7IYgTKpQACrPI9iRWiUdz1z5H/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json"