name: Backend CI/CD (Pipenv)

on:
  push:
    branches:
      - "**"       
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run tests (Pipenv)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies (Pipfile)
        run: |
          pipenv install --dev

      - name: Run tests
        run: |
          pipenv run pytest tests/ -v

